### ISSUE TITLE
TypeError when running main.py

### ISSUE THREAD

**Issue by wulai-econcs** [mariru/dynamic_bernoulli_embeddings#3]
After preprocessing the text data, when run main.py it throws a TypeError as following:
TypeError: Value passed to parameter 'multiples' has DataType float32 not in list of allowed values: int32, int64

The full Traceback is as following:
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    m = define_model(args, d, dir_name)
  File "C:\data\subtitles\processed\dynamic_bernoulli_embeddings\src\models.py", line 350, in define_model
    m = dynamic_bern_emb_model(args, d, logdir)
  File "C:\data\subtitles\processed\dynamic_bernoulli_embeddings\src\models.py", line 251, in __init__
    columns = tf.tile(tf.expand_dims(tf.range(0, self.n_minibatch[t]), [1]), [1, self.cs/2])
  File "C:\Users\kaizhu\.virtualenvs\py3\py3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 10032, in tile
    "Tile", input=input, multiples=multiples, name=name)
  File "C:\Users\kaizhu\.virtualenvs\py3\py3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 609, in _apply_op_helper
    param_name=input_name)
  File "C:\Users\kaizhu\.virtualenvs\py3\py3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'multiples' has DataType float32 not in list of allowed values: int32, int64

**Comment by rmcalexander** [comment]
I'm having the same issue as well!
